---
dist: xenial

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.7.*
  - ANSIBLE_VERSION=2.6.*
  - ANSIBLE_VERSION=2.5.*

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then ansible-lint .; fi
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
